apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tinyrubyapp.fullname" . }}
  labels:
    {{- include "tinyrubyapp.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": "keep"
data:
  {{- toYaml .Values.envVars | nindent 2 }}
