name: Publish Docker image

on:
  push:
    branches:
      - "prod"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Context
        run: "docker context create tinyrubyapp"

      - name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          endpoint: tinyrubyapp

      - name: Build and push
        id: docker_build_client
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          build-args: |
            SECERT_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}
          push: true
          tags: "ejmooney/tinyrubyapp:sha-${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update and Push image tag
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          yq -i '.image.tag = "sha-${{ github.sha }}"' 'chart/tinyrubyapp/values.yaml'
          git config user.email "ejmooney@gmail.com"
          git config user.name "GHA"
          git add chart/tinyrubyapp/values.yaml
          git commit -m "GHA: Update tag to ${{ github.sha }}"
          git push origin HEAD:prod -f
